### ISSUE TITLE
Feature: Access to kimai with http-basic-auth

### ISSUE THREAD

**Issue by neufeind** [gsantner/kimai-android#1]
I'm not able to connect to a kimai behind http-basic-auth. Would it be possible to use the same username/password from the settings also for that login?

**Comment by gsantner** [comment]
Should be possible, but would be better to have an seperate option, because basic-auth and kimai login can be different. 
I am currently busy with university, and welcome **PR**'s. <https://stackoverflow.com/a/21187593> should have the needed code.

**Comment by gsantner** [comment]
Exported to GitLab > <https://gitlab.com/sangre/kimai-android/issues/1>

**Comment by gsantner** [comment]
@neufeind 
Is there still interest in this feature?

**Comment by neufeind** [comment]
It's still an issue that prevents me from using the app, and I have that scenario as a testcase. But it's not something that was high on my prio-list and I didn't find the time myself to work on it/create a PR - sorry for that. If you would have a test-build, I'll be happy to give it a try of course.

**Comment by gsantner** [comment]
This was implemented in <https://github.com/gsantner/kimai-android/commit/98c3f4c0510b5bb3bb61153a5d27488922cf1af8>
