### ISSUE TITLE
Support download of files from WebView

### ISSUE THREAD

**Issue by gsantner** [gsantner/kimai-android#14]
Currently there is no popup or like that asking for download when clicking on something downloadable in android webview. Resolving this will show such a dialog and will save the files in to device external Downloads folder. You need to also ask for EXTERNAL_STORAGE / check permission before saving (marshmallow permissions).

For Kimai you can create an demo account ( it's just one click, no need to enter details) at <https://demo.kimai.org/status.php> (and enter the generated account details in app settings) , goto export in the web menu, select an entry and click e.g. PDF. On desktop this then opens a download dialog for the invoice.pdf, on kimai-android app there is no such thing, nothing happens currently.

**Comment by gsantner** [comment]
If you need more information ask. This issue is an idea, and about people to start contributing to the project. It has not much information because I pasted many ideas/issues and just let them out at the same time :). If you are interested in working on this, and have questions I can give you more details on this.

Register on https://hacktoberfest.digitalocean.com/, send a PR to fix this and get your t-shirt for free (4 accepted PRs to same or different GitHub repositories needed)  :). You have to mention the issue number in the commit/PR (e.g. `fix #20` / `about #8`) Find more hacktober issues from my projects: <https://github.com/search?&q=label%3Ahacktoberfest+user%3Agsantner>

**Comment by a-u-bello** [comment]
Just wondering, should the dialog box ask only for the file to be downloaded or also give the user the option to select the destination?

Am working on showing only a simple dialog box- just yes or no, is that okay?

**Comment by gsantner** [comment]
Yeah, simple download is enough.

just ask for `external storage/downloads` permission and save there. if user denies request maybe save to private cache directory.

also be sure to not overwrite files, but chose an postfix if already exists.. so given invoice.pdf exists -> name it invoice(1).pdf, if that exists invoice(2).pdf

**Comment by gsantner** [comment]
in the dialog you can show e.g. too the download filename, and if somehow posible the filesize (getContentSize()). I don't want to give too much restrictions, try what you think fita best 😉😀

haply hacking 👍

**Comment by a-u-bello** [comment]
Okay, will get to it then.

😎 Already happy with the hacking.

**Comment by gsantner** [comment]
tell me if you need more info

**Comment by a-u-bello** [comment]
Okay will do. 
Having a blocker currently, hoping to fix it today though.

**Comment by gsantner** [comment]
no stress

**Comment by a-u-bello** [comment]
I have implemented an alert dialog to intercept downloads telling the user the file name and size (since am using the download request and manager the file does not overwrite existing file - it append a number to the file name), i have also sorted out permissions on android M and above but the clicking on the OK button on the dialog box displayed doesn't trigger a call to the download listener set on the webView.

I have tried the same code with some other sites and it works fine, but haven't been able to get it to work for kimai.

**Comment by gsantner** [comment]
I think you have to download the file yourself, because Downloadmanager has no access to cookies of the webview and thus download is not possible because of missing authentication.

You can use FileUtils and NetworkUtils.java from e.g. my MemeTastic project, which has most things for download implemented with one call

**Comment by a-u-bello** [comment]
Okay will go through the project. 
I haven't been able to understand how the download is triggered after the OK button is clicked: on the browser it opens a new tab briefly before closing it and the download starts but the download link is never visible, i have tried creating a new window in the webView when the OK button is clicked but it just opens a blank new window, doesn't close and no download is triggered

**Comment by gsantner** [comment]
google and stackoverflow gonna help you out ;)

webview.setDownloadListener sounds like a good entrypoint

**Comment by a-u-bello** [comment]
Lol, okay. Making progress already

**Comment by a-u-bello** [comment]
Could'nt implement this, narrowed the problem to the difference to the header returned on webview and on other browser but could not get the webview to get the same header as a desktop browser despite changing the user agent

**Comment by gsantner** [comment]
Ok. Just a note: there should be zero difference in the normal kimai interface, as it's not diffentiating between screen sizes and user-agents. There is e.g. no adoption when viewing on mobile, so it should be working exactly the same.

**Comment by a-u-bello** [comment]
That's what thought but take a look at headers received when i try to download a document

Firefox on ubuntu

https://demo.kimai.org/extensions/ki_export/processor.php`

POST /extensions/ki_export/processor.php HTTP/1.1
Host: demo.kimai.org
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-ZA,en-GB;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded
Content-Length: 425
Referer: https://demo.kimai.org/core/kimai.php
Cookie: kimai_key=RN3pESNxpM9AxIzQCCuHJ5TbcVpdwd; kimai_user=user_4S; ki_active_tab_target_737984411=5; ki_active_tab_path_737984411=../extensions/ki_export/init.php; ki_active_tab_target_541355053=5; ki_active_tab_path_541355053=../extensions/ki_export/init.php; adminPanel_extension_activePanel_541355053=1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
axAction=export_csv&axValue=%7C%7C%7C&first_day=1506726000&last_day=1508108400&axColumns=date%7Cfrom%7Cto%7Ctime%7Cdec_time%7Crate%7Cwage%7Cbudget%7Capproved%7Cstatus%7Cbillable%7Ccustomer%7Cproject%7Cactivity%7Cdescription%7Ccomment%7Clocation%7CtrackingNumber%7Cuser%7Ccleared&timeformat=H%3AM&dateformat=%25d.%25m.&default_location=&filter_cleared=-1&filter_refundable=-1&filter_type=-1&column_delimiter=%2C&quote_char=%22: undefined


Android Webview:
Referer=https://demo.kimai.org/core/kimai.php, 
Origin=https://demo.kimai.org,
 Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8, 
Content-Type=application/x-www-form-urlencoded, 
User-Agent=Mozilla/5.0 (Linux; Android 7.1.1; Google Nexus 5X - 7.1.0 - API 25 - 1080x1920 Build/NMF26Q; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.100 Mobile Safari/537.36, 
Upgrade-Insecure-Requests=1

Notice the missing axAction field from the desktop header

**Comment by gsantner** [comment]
hm weird.. and the builtin download-callback of webview does not get called?

**Comment by a-u-bello** [comment]
Nope it doesn't, kinda feel it's out of my scope cos from observation the main content to be downloaded is contained in the axAction field which is missing

**Comment by gsantner** [comment]
I've looked into this, so:

* The download button makes a POST call to /extensions/ki_export/process.php
* POST requests are not intercept(able) by any webview functionality
* Only GET requests reach downloadmanager
* -> This is not possible without a big workaround...

**Comment by a-u-bello** [comment]
Lol, thought as much.

The easiest way out is if the backend can make the download compatible with webview, say the download button simply makes a get request for the selected file.
