### ISSUE TITLE
Strange default screen

### ISSUE THREAD

**Issue by imme-emosol** [gsantner/kimai-android#22]
When using the app for the first time, I see:
```
No valid path

Please check your settings!
```
This was confusing because I did not know I could swipe from the left to get access to a menu.

**Comment by gsantner** [comment]
There should be a green bottom on the bottom right too when starting first, which also opens nav-drawer, so there should be at least some UI :)

**Comment by imme-emosol** [comment]
Perhaps there was on the very first time .. but I had only looked at it that time and tried some things .. but then left it alone for quite a while until now installing my own kimai-service and stuff.

**Comment by gsantner** [comment]
I can turn the option from first-always+opt-in to a general opt-out - will this make it better?

**Comment by imme-emosol** [comment]
I think it would.

You can't change that is shown?

Because leaving the opt-in/-out the same but changing the text might solve it as well, i.e.:

> Please use the swipe menu on the left to check your settings!

**Comment by gsantner** [comment]
I can do anything :D. If you want, you can send me a PR to improve the english version of the string, located here <https://github.com/gsantner/kimai-android/blob/master/app/src/main/res/values/strings.xml#L16>. You can append ther ewhat you think fits best, e.g. use bottom button, navdrawer, settings

**Comment by imme-emosol** [comment]
ok https://github.com/gsantner/kimai-android/pull/23 :)

**Comment by imme-emosol** [comment]
thanks!

**Comment by gsantner** [comment]
myabe error_incomplete_login_data would be better explaining what is wrong. The current is there since versioncode 1 :D.
