### ISSUE TITLE
NO VALID PATH FOUND  !!!

### ISSUE THREAD

**Issue by FrankD11** [gsantner/kimai-android#29]
Hi I had previouly installed the app before installing kimai server side so it didn't work!!!

Now the back end is working and all I get when I run the app is a white page witch tells me that 
NO VALID PATH verify settings

I have tried reinstalling to no avail

Thanks for the help
Regards

**Comment by gsantner** [comment]
You have to set paths and login data in settings. Profile 1 should be the default.

**Comment by FrankD11** [comment]
Ok got it thank a Million

**Comment by gsantner** [comment]
np
