### ISSUE TITLE
WebView content get lost after device rotation

### ISSUE THREAD

**Issue by calbee633810** [gsantner/kimai-android#30]
#### General information

* **App version:** 
v1.3.12 (25) 
* **System:** 
Android 6, Nexus 4

#### Description
Open app, rotate device twice.

The green ball at the right bottom part of the screen disappear, thus I can't do anything with the app.

![screen shot 2018-04-12 at 10 06 08 pm](https://user-images.githubusercontent.com/38213896/38682617-20ab1f4e-3e9e-11e8-8947-bcc672c2feee.png)
Screenshot before rotation

![screen shot 2018-04-12 at 10 06 26 pm](https://user-images.githubusercontent.com/38213896/38682625-24d5f9ae-3e9e-11e8-83a1-d6db5b7ca75a.png)
Screenshot after the rotation

**Comment by gsantner** [comment]
Good catch! Having always rotation lock on so didn't quite get that yet.

Happy about PRs ;)

**Comment by gsantner** [comment]
I'm closing this as the app isn't updated for Kimai v2. And probably never will unless somebody is so friendly to start contributing. I myself don't use Kimai anymore, and as far I can see there haven't been any community interest/contribution in the past...so likely this won't ever happen.
