### ISSUE TITLE
FR: Mobile friendly interface

### ISSUE THREAD

**Issue by gerroon** [gsantner/kimai-android#33]
#### General information
Lollipop

* **App version:** 
1.3.13

* **System:** 
Debian Wheezy

#### Description
HI

Is it possible to make this a app abit more phone screen size friendly? Everything is very small atm. It would be nice if the mobile version rescales the ui and offers bigger fonts.

thanks

**Comment by gsantner** [comment]
I'm closing this as the app isn't updated for Kimai v2. And probably never will unless somebody is so friendly to start contributing. I myself don't use Kimai anymore, and as far I can see there haven't been any community interest/contribution in the past...so likely this won't ever happen.
