### ISSUE TITLE
New kimai-android strings translatable

### ISSUE THREAD

**Issue by gsantner** [gsantner/kimai-android#8]
This issue will be used to notify translators of the app. Please subscribe to this issue if you want to start translating or already translated something and want to keep the strings updated for some language.

You can use e.g. [Stringlate](https://f-droid.org/packages/io.github.lonamiwebs.stringlate/) to contribute translations - directly on your phone.

 [![Translate - with Stringlate](https://img.shields.io/badge/stringlate-translate-green.svg)](https://lonamiwebs.github.io/stringlate/translate?git=https%3A%2F%2Fgithub.com%2Fgsantner%2Fkimai-android.git&name=kimai-android&web=https%3A%2F%2Fgithub.com%2Fgsantner%2Fkimai-android) 

List of translators on GitHub (unified across @gsantner projects):
* German - @gsantner
* French - @milouse, @Poussinou, @Quent-in, @SansPseudoFix, @gbaudic
* Russian - @xredor, @guland2000
* Spanish - @larjona, @Lonami, @AlexandreInsua
* Italian - @simocosimo, @Daraf-IT, @xDarkWolf
* Brazilian - @luisfsr, @TiagoDanin
* Swedish - @spitlo
* Turkish - @mobile46
* Polish - @kRkk, @pskosinski, @Bjornskjald
* Ukrainian - @cl0ne, @Abrasha
* Hindi - @kartikarora
* Japanese - @naofum
* Sardinian - @asereze
* Greek - @nicolasmanic
* Dutch - @TopdRob
* Indonesian - @freedomofkeima
* Hungarian - @maxigaz

**Comment by gsantner** [comment]
Hi all, hacktober approaches :)

Register on <https://hacktoberfest.digitalocean.com/>, send a PR to update translations and get your t-shirt for free :).

**Comment by freedomofkeima** [comment]
Hi @gsantner ,

I'll start working with Indonesian translation and I'll send a PR soon :)

**Comment by Bjornskjald** [comment]
@gsantner submitted Polish translation.

**Comment by Daraf-IT** [comment]
There is something to translate here in Italian language??

**Comment by gsantner** [comment]
italian is already finished :)

**Comment by nicolasmanic** [comment]
I will start working on a Greek translation.

**Comment by AlexandreInsua** [comment]
I wil start working on a Spanish translation

**Comment by Abrasha** [comment]
Hi @gsantner (one more time)! Would you like to translate your app to Ukrainian? I have already done it for [Stringlate](https://github.com/LonamiWebs/Stringlate/pull/147)

**Comment by gsantner** [comment]
go for it :D

**Comment by Abrasha** [comment]
Hi @gsantner. Do we need to place `hacktoberfest` label on related PRs?

**Comment by gsantner** [comment]
No. As far as I understood there is nothing needed, not even on issues. The tag is just for people easier to find hacktoberfest tasks. the page just says "4 PRs", nothing else

**Comment by Abrasha** [comment]
Ah, I understood. I believe that they automatically track registered (for hacktoberfest) users for PRs. Makes sense.
